### PR TITLE
fix encapsulation and validation

### LINKED ISSUE #4: Fix encapsulation in classes
Change access modifiers to encapsulate logic and fields inside classes. Might want to do this after implementing the Cli class.

### PR DESCRIPTION
**Pull request by yumyum-web**
Closes: #4

### CODE REVIEW

File: src/game/Player.java [hunk 1]
```diff
@@ -48,12 +48,18 @@ public int getXp() {
...
+        this.xp += delta;
     }
 
-    public double getGoldCoins() {
-        return goldCoins;
+    public int getGoldCoins() {
+        return this.goldCoins;
+    }
+
+    private void changeGoldCoins(double delta) {
```
Comment (yumyum-web) [inline src/game/Player.java]: This should be a public method
```suggestion
    public void changeGoldCoins(double delta) {
```
